### ISSUE TITLE
noTitleBar-All applications

### ISSUE THREAD

**Issue by joelbrewster** [cHoco/noTitleBar-Terminal#3]
Hey cHoco,
Are there any plans to extend the noTitleBar app to extend to more mac OS X applications?

**Comment by choco** [comment]
Hi, while the basic process can be replicated for almost any application, every application has different code for when a window enters or exits fullscreen, or when a new window is created, etc... So a general approach would probably do more harm than good, or it would probably require more time that I can spare at the moment.

Maybe by modifying the code in NSThemeFrame (the class that backs all windows on OS X, and that draw the titlebar etc...) we could achieve a better result, but I don't have time to take a look at that for the moment :(
Finally, if there some specific application that you'd like to see without titlebar I can take a look and apply a similar hack I use with terminal.

**Comment by joelbrewster** [comment]
Ah, that's too bad. Well, on a separate topic; do you think it'd feasible to hide the close, minimize and maximize buttons with SIMBL?

**Comment by choco** [comment]
Sorry for never getting back, the buttons can surely be hidden using SIMBL but the same problems above would stand, the best way would probably be to mess with NSThemeFrame directly.
