### ISSUE TITLE
noTitleBar on Mavericks

### ISSUE THREAD

**Issue by CharlesBoury** [cHoco/noTitleBar-Terminal#4]
Hello !
I'm trying noTitleBar on Mac OS 10.9, and getting an error :/
The terminal starts, then I see it remove its titlebar, and crash right after.
The milliseconds of displaying look like this :
![screen shot](https://cloud.githubusercontent.com/assets/2370905/18038426/3d8dafa6-6d98-11e6-8af5-933d5c5786d6.jpg)

Did someone tested it on other versions than El Capitan ?
If you know it doesn't work on older versions, how hard would it be to make it work on 10.9 ?

Thanks !

**Comment by choco** [comment]
Hi, I don't think anyone tested on older versions of of OS X, but it should work with every version after Yosemite. I use some APIs and mask values for NSWindow that were only introduced in that version.

Can you try v0.2 bundle? That one just removed window decoration (including titlebar) completely and should be compatible with Mavericks (albeit it doesn't have padding...)
Unfortunately I don't have a lot of free time so I'm not sure I'll be able to fix this in a timely manner, but the crash report would be really helpful.
