### ISSUE TITLE
add recommended install for sierra to readme

### ISSUE THREAD

**Issue by thejmazz** [cHoco/noTitleBar-Terminal#6]
I had a little bit of trouble setting up simbl, 
seems SIMBL-0.9.9 doesn't work on sierra.
(that is, [these instructions](https://github.com/norio-nomura/EasySIMBL/issues/26#issuecomment-117028426) did not work for me)

In any case, I ended up getting it to work by installing mySIMBL and then restarting

figured there would be no harm if you had a line recommending mySIMBL for sierra users,
as this was my first time using SIMBL and had to dig around a bit before finding something that worked.

https://github.com/w0lfschild/mySIMBL

cheers, really liking this plugin.

*aside*
the "text rendering" you refer to [here](https://github.com/koekeishiya/kwm/issues/2#issuecomment-187376526), do you mean how it is "bolder" ? seems to be that the way terminal.app antialiases text on retina kinda makes it look bolder (see [this](https://discussions.apple.com/thread/6123987?tstart=0) ). wondering if that's what you meant, or something else. personally, I like it sharper like in iTerm, but with a bit smaller font size its manageable. and worth it for ligatures

**Comment by nhooyr** [comment]
The text rendering is fixed in iTerm2 now.

**Comment by choco** [comment]
Sorry for getting back so late, the project has been dead for quite a while since, as @nhooyr mentioned, iTerm2 now renders text the same way as Terminal, plus is much easier to patch around to make it behave like I want.
